### PR TITLE
Separate modules for each command

### PR DESCRIPTION
**Pull request by adnan007d**
Separate modules for each command and changed from discord.Client() to discord.ext.commands.Bot()

### CODE REVIEW

**Comment by ricardoprins** [comment]
This looks amazing. @gat786 can you test it?

**Comment by gat786** [comment]
Oo I will have to manually run and check its working. On it!

**Comment by anushkrishnav** [comment]
Much need Awesome work

**Comment by gat786** [comment]
I had just tested the build as well as functioning locally and it works great.

**Pull request merged**
