### PR TITLE
feat: new directory structure + quotes API

### PR DESCRIPTION
**Pull request by KamalDGRT**
## Related Issues or Pull Requests

#56 #35 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/Ric-Bot/blob/main/CONTRIBUTING.md)?

Yes. I have. 😄 

### Description

- I moved the files that are not `cogs` and added them to a separate folder
- Fetching quotes from an API instead of random hard-coded values

### Checklist

-   [x] I've read the contribution guidelines.
-   [x] I've checked the issue list before deciding what to submit.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generate no new warnings.
-   [x] I've followed 4 space indentation throughout the file(s).
-   [x] My code follows the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guidelines.
-   [x] I have made corresponding changes to the documentation.
-   [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works.

#### File(s) Added / Modified

-   `src/main.py` (Modified)
-   `src/modules/commands.py ` (Added few event listeners)
-   `src/modules/memes.py` (Modified to fetch the API keys)
-   `src/modules/quotes.py` (Modified to fetch quotes from API's)
-    Moved these files to `src/utils/` directory:
    - `__init__.py`
    - `client.py`
    - `settings.py`
    - `log.py`

#### Language(s) Used

-   Python

#### Screenshots

Testing out the existing features with the new structure:

Feature Test

Checking out the Quote Feature:

Quotes Feature

### CODE REVIEW

**Comment by adnan007d** [comment]
Great Work! The Embed on quote is awesome.
Overall code looks good to me

**Comment by KamalDGRT** [comment]
Thanks! So, shall we merge it then?

**Comment by adnan007d** [comment]
Two small problems
1) In help function the command name is !quotes and in the cog module command name is !quote. (Change either one)
2) Line 25 of commands.py is not needed as its raising and error and the line after it does the job of showing the exact command which was not found.
If this is solved, I think we are good to merge it

**Comment by KamalDGRT** [comment]
I have done the changes that you have mentioned.
And as for the `!help` command, we can implement that for every other command that we have.
Like, with its usage and stuff.
I will raise an issue regarding the same.

**Comment by adnan007d** [comment]
Yes that would be great and also add an embed in it too.
For this PR I think everything is good and we can merge it

**Comment by KamalDGRT** [comment]
Okayy. I am merging the PR then!

**Pull request merged**
