### PR TITLE
Feature to flag offensive words

### PR DESCRIPTION
**Pull request by adnan007d**
## Related Issues or Pull Requests

Flag offensive words 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/Ric-Bot/blob/main/CONTRIBUTING.md)?

Yup

### Description

Deleting messages which contains offensive words and raising a warning

### Checklist

-   [x] I've read the contribution guidelines.
-   [x] I've checked the issue list before deciding what to submit.
-   [x] I have performed a self-review of my own code.
-   [x] I have commented my code, particularly in hard-to-understand areas.
-   [x] My changes generate no new warnings.
-   [x] I've followed 4 space indentation throughout the file(s).
-   [x] My code follows the [PEP8](https://www.python.org/dev/peps/pep-0008/) style guidelines.

#### File(s) Added / Modified

-   `client.py`
-   `offensive.py`
-   `offensive.json`

#### Language(s) Used

-   Python

### CODE REVIEW

**Comment by gat786** [comment]
oh sweet let me have a dry run of this.

**Comment by gat786** [comment]
It would have been best if we had some tests for this mechanism.

**Comment by gat786** [comment]
@adnan007d I have tested it a little bit and what I noticed is that it raises an error if it doesn't have enough perms. From a user experience point of view the admin/moderator won't know what went wrong when it was not able to delete an inappropriate message. So my suggestion is that if the bot was unable to delete a message it should send a message that 
`Abusive content found but not enough permissions available to delete the message` and if possible reply to the abusive message while doing so. Also We are also deleting the message where bot gives a warning about abusive message I think it should remain there and not get deleted. It would help moderators see who has received how many warnings.

**Comment by adnan007d** [comment]
Sure I'll work on it and I think in antispam also we need to raise a warning.

**Comment by gat786** [comment]
It  works like a charm

**Review by gat786 — APPROVED** [review]

**Pull request merged**
